
TWITTER_CONSUMER_KEY = '7imtJmvIFxQsIVjDoMRrTMuEE' #api key
TWITTER_CONSUMER_SECRET = 'wOEUCLjp0fThsXvhosSyjHJ5bnQTZcExuOgNefWSK0cwzBmcCw' #API secret key
TWITTER_ACCESS_TOKEN = '590269010-W0DmEDTNK32sU63Sgyn7TyxkfQV7Wi2UXI4Edx7j'   # ACCESS TOKEN
TWITTER_ACCESS_TOKEN_SECRET = 'J4GkMWUNRzHtThC6LZ9SyajnK19HlfklZGFHs999dUUMh'   # SECRET TOKEN
